require 'puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'

PuppetLint.configuration.with_filename = true
PuppetLint.configuration.fail_on_warnings = true

HERE = File.expand_path(File.dirname(__FILE__))

desc "Run puppet-lint"
task :lint do
  $stderr.puts '---> lint:tests'

  linter = PuppetLint.new
  matched_files = FileList['**/*.pp']

  matched_files.each do |puppet_file|
    linter.file = puppet_file
    linter.run
  end

  fail if linter.errors?
end

task :default => [:lint]